### PR TITLE
Fix ReSpec - conformance section

### PR DESCRIPTION
**Pull request by eladalon1983**
***
<a href="https://pr-preview.s3.amazonaws.com/eladalon1983/mediacapture-region/pull/39.html" title="Last updated on Mar 31, 2022, 6:30 PM UTC (66f599c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-region/39/efc006b...eladalon1983:66f599c.html" title="Last updated on Mar 31, 2022, 6:30 PM UTC (66f599c)">Diff</a>

### CODE REVIEW

**Comment by eladalon1983** [comment]
Otherwise, it complains: `Reference "[WebIDL]" not found.`

**Review by dontcallmedom — CHANGES_REQUESTED** [review]
I believe this is a bug in ReSpec rather than in this document; I'll go and try to get it fixed upstream instead

**Comment by dontcallmedom** [comment]
with https://github.com/w3c/respec/pull/4112 now merged, the respec bug is gone and I believe this PR can be closed unmerged.

**Comment by eladalon1983** [comment]
Thank you, @dontcallmedom!

**Pull request closed without merging**
